version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - homex
      - homey

  homex:
    build: ./homex
    depends_on:
      - homey
    ports:
      - "3500:5000"

  homey:
    build: ./homey
    depends_on:
      - homez
    environment:
      PGUSER: homez
      PGHOST: homez
      PGPASSWORD: homez123
      PGDATABASE: homez
      NODE_ENV: production
    ports:
      - "3666:3666"
      - "3667:3667"

  homez:
    build: ./homez
    ports:
      - "3665:5432"
    environment:
      POSTGRES_PASSWORD: post123
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
